# Generated by Django 2.1.7 on 2020-04-16 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authAB_', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('classCode', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authAB_.Teacher')),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='authAB_.Student')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
            },
        ),
        migrations.CreateModel(
            name='NewsDiscussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AbstractPostDiscussionOwner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NewsDiscussion',
                'verbose_name_plural': 'NewsDiscussions',
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='news_posts')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NewsPost',
                'verbose_name_plural': 'NewsPosts',
            },
        ),
        migrations.CreateModel(
            name='StudentWorkDiscussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StudentWorkDiscussionWithReplyOwner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'StudentWorkDiscussion',
                'verbose_name_plural': 'StudentWorkDiscussion',
            },
        ),
        migrations.CreateModel(
            name='StudentWorkPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='student_work_posts')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'StudentWorkPost',
                'verbose_name_plural': 'StudentWorkPosts',
            },
        ),
        migrations.AddField(
            model_name='studentworkdiscussion',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.StudentWorkPost'),
        ),
        migrations.AddField(
            model_name='studentworkdiscussion',
            name='sendTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_owner_send_to', to='authAB_.Teacher'),
        ),
        migrations.AddField(
            model_name='newsdiscussion',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.NewsPost'),
        ),
    ]
