# Generated by Django 2.1.7 on 2020-04-16 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authAB_', '0002_auto_20200416_1349'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentWorkDiscussionWithReply',
            new_name='StudentWorkDiscussion',
        ),
        migrations.RemoveField(
            model_name='studentworkdiscussionwithoutreply',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='studentworkdiscussionwithoutreply',
            name='post',
        ),
        migrations.DeleteModel(
            name='StudentWorkDiscussionWithoutReply',
        ),
    ]
