# Generated by Django 2.1.7 on 2020-04-16 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200416_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentworkdiscussion',
            options={'verbose_name': 'StudentWorkDiscussion', 'verbose_name_plural': 'StudentWorkDiscussion'},
        ),
        migrations.AlterField(
            model_name='newspost',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentworkpost',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
