# Generated by Django 2.2.4 on 2020-04-26 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200423_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentworkpost',
            name='lesson',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.Lesson'),
        ),
    ]
