# Generated by Django 2.2 on 2020-04-16 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200416_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentworkdiscussion',
            options={'verbose_name': 'StudentWorkDiscussion', 'verbose_name_plural': 'StudentWorkDiscussion'},
        ),
    ]
