# Generated by Django 2.2 on 2020-04-17 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200416_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdiscussion',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AbstractPostDiscussionOwner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentworkdiscussion',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StudentWorkDiscussionWithReplyOwner', to=settings.AUTH_USER_MODEL),
        ),
    ]
