# Generated by Django 2.2 on 2020-04-26 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lastnotificationstudentworkpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastNotificationStudentWorkDiscussions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_discussions', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.StudentWorkDiscussion')),
            ],
            options={
                'verbose_name': 'LastNotificationStudentWorkPostDiscussion',
                'verbose_name_plural': 'LastNotificationStudentWorkPostsDiscussions',
            },
        ),
    ]
