# Generated by Django 2.1.7 on 2020-04-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAB_', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='level',
            field=models.IntegerField(choices=[(1, 'Associate degree'), (2, 'Bachelor degree'), (3, 'Master degree'), (4, 'Doctoral degree')], max_length=200),
        ),
    ]
