# Generated by Django 2.2.4 on 2020-04-14 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authAB_', '0002_student_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='studenty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studenty', to='authAB_.Student'),
        ),
    ]
