# Generated by Django 2.1.7 on 2020-04-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAB_', '0002_auto_20200417_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='level',
            field=models.CharField(choices=[('Associate degree', 'Associate degree'), ('Bachelor degree', 'Bachelor degree'), ('Master degree', 'Master degree'), ('Doctoral degree', 'Doctoral degree')], max_length=200),
        ),
    ]
