# Generated by Django 2.2 on 2020-04-15 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('core', '0003_auto_20200415_1907'),
        ('auth', '0011_update_proxy_permissions'),
        ('authAB_', '0003_auto_20200415_0341'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='User',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
